SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS borrows;

CREATE TABLE borrows (
    id int PRIMARY KEY AUTO_INCREMENT,
    user_id int NOT NULL,
    book_id int NOT NULL,
    borrowed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    returned_at TIMESTAMP NULL,

    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

SET FOREIGN_KEY_CHECKS=1;